version: '3.8'
services:
    web:
        container_name: pyrrha
        build: .
        environment: 
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
        command: gunicorn --bind 0.0.0.0:5000 wsgi
        volumes:
        - .:/code
        ports:
        - "5000:5000"